# Generated by Django 3.2.5 on 2022-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_uploaded',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
