# Generated by Django 3.2.5 on 2022-02-07 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0002_task_image_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image_uploaded',
        ),
        migrations.CreateModel(
            name='ImageFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameimage', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=200)),
                ('imagedescription', models.TextField(max_length=254)),
                ('image_uploaded', models.ImageField(null=True, upload_to='images')),
                ('taskuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
