# Generated by Django 3.2.5 on 2022-02-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_auto_20220208_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefromuser',
            old_name='taskuser',
            new_name='imageuser',
        ),
    ]
