# Generated by Django 3.2.5 on 2022-02-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_rename_taskuser_imagefromuser_imageuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefromuser',
            name='docfile',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
