# Generated by Django 3.2.5 on 2022-02-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_remove_imagefromuser_nameimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefromuser',
            name='date_uploaded',
            field=models.DateField(auto_now=True),
        ),
    ]
